name: Merge master to development

on:
  push:
    branches:
      - master

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Merge master to development
        uses: devmasx/merge-branch@854d3ac71ed1e9deb668e0074781b81fdd6e771f # v1.4.0
        with:
          type: now
          from_branch: master
          target_branch: development
          message: Merge master to development
          github_token: ${{ secrets.GITHUB_TOKEN }}