name: TypeScript check

on:
  push:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    
    - name: Setup Node.js
      uses: actions/setup-node@v4.4.0
      with:
        node-version: '24'

    - name: Install dependencies
      run: npm i

    - name: Build the application
      run: npm run build

    - name: TypeScript check
      run: npm run tsc