name: TypeScript check

on:
  pull_request:
    state: open

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v1.4.0
    
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: '24'

    - name: Install dependencies
      run: npm i

    - name: Build the application
      run: npm run build

    - name: TypeScript check
      run: npm run tsc